<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Utility>
 */
class UtilityFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $utility = [
            'Water supply',
            'Electricity',
            'Gas connection',
            'Sewage system',
            'Internet service',
            'Telephone lines',
            'Street lighting',
            'Trash collection',
            'Security system',
            'Garden maintenance',
            'Swimming pool',
            'Fitness center',
            'Clubhouse',
            'Tennis court',
            'Basketball court',
            'Playground',
            'Car parking',
            'Cable TV',
            'Laundry facilities',
            'Air conditioning',
            'Heating system',
            'Elevator',
            'Fire alarm system',
            'Waste disposal',
            'Lawn care',
            'Pest control',
            'Community events',
            'Snow removal',
            'Common area cleaning',
            'Water treatment',
            'Gymnasium',
            'Sauna',
            'Steam room',
            'Party hall',
            'Yoga studio',
            'Bicycle storage',
            'Dog park',
            'Roof deck',
            'Electric vehicle charging',
            'EV parking',
            'Guest suites',
            'Concierge service',
            'Valet parking',
            'Shuttle service',
            'Bike-sharing station',
            'Car wash station',
            'Mailroom',
            'Package receiving',
            'Business center',
            'Conference room',
            'Pet grooming',
            'Pet walking service',
            'Dog wash station',
            'Dry cleaning service',
            'On-site maintenance',
            '24-hour security',
            'CCTV surveillance',
            'Smart home features',
            'Wine cellar',
            'Library',
            'BBQ area',
            'Fire pit',
            'Solar panels',
            'Rainwater harvesting',
            'Waterfront access',
            'Marina',
            'Boat storage',
            'Fishing dock',
            'Hiking trails',
            'Bocce court',
            'Golf course',
            'Green space',
            'Nature reserve',
            'Picnic area',
            'Recreation room',
            'Arcade room',
            'Cinema room',
            'Music studio',
            'Art studio',
            'Catering kitchen',
            'Guest parking',
            'Dog-friendly areas',
            'Pet play area',
            'Courtyard',
            'Private garden',
            'Fitness classes',
            'Convenience store',
            'Beauty salon',
            'Restaurant',
            'Coffee shop',
            'Barbecue pits',
            'Rooftop garden',
            'Playroom',
            'Outdoor pool',
            'Indoor pool',
            'Jacuzzi',
            'Library',
            'Putting green',
            'Skate park',
            'Amphitheater',
            'Dog agility course',
            'Outdoor movie theater',
        ];
        return [
            'name' => $this->faker->unique()->randomElement($utility),
        ];
    }
}
